config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'}

  devise_scope :user do
    root to: "devise/sessions#new"
    get "sign-in", to: "devise/sessions#new"
    get "sign-out", to: "devise/sessions#destroy"
  end

  get "dashboard" => "static_pages#dashboard"
  get "contacts" => "static_pages#contacts"
  get "contacts/profile" => "static_pages#profile"

  resource "calendar" do
    get "/" => "calendar#index"
    get "week" => "calendar#week"
    get "selected-date" => "calendar#selected_date"
    get "feed" => "calendar#export"
  end

  resources :events

  resource "reporting" do
    get "/" => "reporting#index"
  end

  resource "slack" do
    post "message" => "slack#message"
  end

  resource "weather" do
    post "message" => "weather#message"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: :dashboard

  def home
  end

  def dashboard
    @date = Date.today
    @events = Event.all
  end

  def contacts
    @users = User.all.order("display_name ASC")
  end

  def profile
    @user = User.find(params[:u])
    events = Event.where(user_id: params[:u]).order("start_date ASC")

    @events = []
    events.each do |event|
      if Date.strptime(event.start_date, "%m/%d/%Y") >= Date.today || (Date.strptime(event.start_date, "%m/%d/%Y") <= Date.today && Date.strptime(event.end_date, "%m/%d/%Y") >= Date.today)
        @events << event
      end
    end
  end
end

app/views/static_pages/_subnav_contacts.html.erb
<section class="subnav-container contacts-nav row">
  <div class="col-lg-8 col-lg-offset-2">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-8">
          <ul class="list-inline team-filter">
            <li>
              <%= link_to "Lifeblue".upcase, "#", class: "white-link teal-link show-lifeblue" %>
            </li>
            <li>
              <%= link_to "1400", "#", class: "white-link show-1400" %>
            </li>
            <li>
              <%= link_to "Prism".upcase, "#", class: "white-link show-prism" %>
            </li>
            <li>
              <%= link_to "Flux".upcase, "#", class: "white-link show-skyblue" %>
            </li>
          </ul>
        </div>
        <div class="col-xs-4 text-right">
          <ul class="list-inline toggle-views">
            <li>
              <%= link_to "<span class='glyphicon glyphicon-th-large' aria-hidden='true'></span>".html_safe, "#", class: "white-link teal-link show-grid-view" %>
            </li>
            <li>
              <%= link_to "<span class='glyphicon glyphicon-th-list' aria-hidden='true'></span>".html_safe, "#", class: "white-link show-list-view" %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/contacts.html.erb
<% provide(:title, "Contacts") %>

<%= render "static_pages/subnav_contacts" %>
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <div class="contacts-container mtl pbl">
        <div class="contacts-grid-view">
          <div class="container-fluid">
            <div class="row">
              <% @users.each do |user| %>
                <div class="col-md-4 col-sm-6 user-circle" data-user-team="<%= user.team %>">
                  <div class="profile-avatar border-<%= current_availability(user) %>" style="background-image: url('<%= avatar_url(user) %>');">
                    <div class="contact-quick-details-overlay">
                      <div class="contact-quick-details-heading mtl"><%= user.display_name.upcase %></div>
                      <div class="mtxs"><%= link_to user.email, "mailto:#{user.email}" %></div>
                      <div><%= user.phone %></div>
                      <div><%= link_to "View Profile", contacts_profile_path(u: user.id), class: "button button-default button-s mtm" %></div>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="contacts-list-view pbl hidden">
          <div class="table users-list container-fluid">
            <% @users.each do |user| %>
              <div class="user row border-<%= current_availability(user) %>" data-user-team="<%= user.team %>">
                <div class="col-lg-3 col-sm-4 user-avatar-name">
                  <div class="inline-block"><%= image_tag avatar_url(user), class: "profile-avatar" %></div>
                  <div class="inline-block user-name"><%= user.display_name.upcase %></div>
                </div>
                <div class="col-lg-5 col-sm-5 mts user-contact">
                  <div class="inline-block user-email"><%= link_to user.email, "mailto:#{user.email}" %></div>
                  <div class="inline-block user-phone"><%= user.phone %></div>
                </div>
                <div class="col-lg-4 col-sm-3 text-right mtxs user-profile">
                  <%= link_to "view profile", contacts_profile_path(u: user.id), class: "button button-default button-s mtxs" %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/dashboard.html.erb
<% provide(:title, "Dashboard") %>

<div class="row">
  <div class="col-lg-8 col-lg-offset-2">
    <div class="dashboard-container mtm">
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

app/views/static_pages/profile.html.erb
<% provide(:title, "#{@user.display_name} | Contacts") %>

<div class="profile-container row">
  <div class="col-lg-12">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <div class="profile-banner" style="background-image: url('<%= !@user.profile_banner.blank? ? @user.profile_banner : "http://placehold.it/1600x400/333333/999999&text=Banner"  %>');">
          </div>
          <div class="profile-avatar border-<%= current_availability(@user) %>" style="background-image: url('<%= avatar_url(@user) %>');">
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <div class="profile-information">
            <div class="profile-name">
              <%= @user.display_name.upcase %>
            </div>
            <div class="profile-team">
              <%= @user.team.upcase %>
            </div>
            <div class="profile-email">
              <%= link_to @user.email, "mailto:#{@user.email}" %>
            </div>
            <div class="profile-phone">
              <%= @user.phone %>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12 profile-quote">
          <%= @user.quote %>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12 profile-upcoming-events">
          <h3 class="mtn">
            <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> UPCOMING
          </h3>
          <% @upcoming_events = upcoming_events_grouped_by_month(@events) %>
          <% @upcoming_events.each do |month, dates| %>
            <table class="upcoming-events-table">
              <tr>
                <td class="upcoming-events-month">
                  <%= month %>
                </td>
                <td></td>
              </tr>
              <% dates.each do |date, events| %>
                <tr>
                  <td class="upcoming-events-day">
                    <%= date.strftime("%d") %>
                  </td>
                  <td class="upcoming-events-list">
                    <ul class="list-unstyled">
                      <% events.each do |event| %>
                        <li class="event">
                          <div class="inline-block availability <%= event.display_event_availability(date) %>"></div>
                          <div class="inline">
                            <%= event.display_as_text(date, false) %>
                            <%= link_to "<span class='glyphicon glyphicon-trash' aria-hidden='true'><span class='sr-only'>Delete Event?</span></span>".html_safe, event_path(event), method: :delete, data: { confirm: "Are you sure you want to delete this event?" } if event.user == current_user || current_user.is_admin? %>
                          </div>
                        </li>
                      <% end %>
                    </ul>
                  </td>
                </tr>
              <% end %>
            </table>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>