config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'}

  devise_scope :user do
    root to: "devise/sessions#new"
    get "sign-in", to: "devise/sessions#new"
    get "sign-out", to: "devise/sessions#destroy"
  end

  get "dashboard" => "static_pages#dashboard"
  get "contacts" => "static_pages#contacts"
  get "contacts/profile" => "static_pages#profile"

  resource "calendar" do
    get "/" => "calendar#index"
    get "week" => "calendar#week"
    get "selected-date" => "calendar#selected_date"
    get "feed" => "calendar#export"
  end

  resources :events

  resource "reporting" do
    get "/" => "reporting#index"
  end

  resource "slack" do
    post "message" => "slack#message"
  end

  resource "weather" do
    post "message" => "weather#message"
  end
end

app/views/shared/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <% if !value.blank? %>
    <article class="<%= flash_class(key) %> alert-dismissable container-fluid">
      <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= value %>
        </div>
      </div>
    </article>
  <% end %>
<% end %>

app/views/shared/_flash_messages_auth.html.erb
<% flash.each do |key, value| %>
  <% if !value.blank? %>
    <article class="<%= flash_class(key) %> alert-dismissable container-fluid">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= value %>
    </article>
  <% end %>
<% end %>

app/views/shared/_header.html.erb
<header class="header">
  <nav class="navbar main-nav-container row">
    <div class="col-lg-8 col-lg-offset-2">
      <nav class="navbar">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to image_tag("icon.png"), dashboard_path, class: "navbar-brand" %>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li>
                <%= link_to "<span class='glyphicon glyphicon-plus text-teal' aria-hidden='true'></span> Add Event".html_safe, "#", id: "new-event", class: "static-popup-link" %>
              </li>
              <li class="<%= current_page?(week_calendar_path) ? "active": "" %>">
                <%= link_to "Week", week_calendar_path %>
              </li>
              <li class="<%= current_page?(calendar_path) ? "active": "" %>">
                <%= link_to "Month", calendar_path %>
              </li>
              <li class="<%= current_page?(contacts_path) ? "active": "" %>">
                <%= link_to "Contacts", contacts_path %>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown weather">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                  <% current_weather %>
                  <%= image_tag("weather-icons/#{@weather["icon"]}.png", alt: @weather["condition"]) %>
                  <%= "#{@weather["temperature"]}&deg;".html_safe %> <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <% weather_forecast %>
                  <% @forecast.each do |day| %>
                    <li class="forecast-day">
                      <h4><%= day.starts_at.strftime("%A") %></h4>
                      <%= image_tag("weather-icons/#{day.icon}.png", alt: day.icon) %>
                      <%= "hi: #{day.high.f}&deg; / lo: #{day.low.f}&deg;".html_safe %>
                    </li>
                  <% end %>
                </ul>
              </li>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                  <%= image_tag avatar_url(current_user), class: "profile-avatar" %> <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li>
                    <%= link_to "Manage Account", edit_user_registration_path %>
                  </li>
                  <li>
                    <%= link_to "Sign Out", sign_out_path %>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
  </nav>
  <%= render "events/new" %>
</header>